Bug: Fix issue with error scope when running EnforceAll
ossf/allstar pull request #219
Opened 2022-06-17 15:51 UTC by markdboyd

While running scans to fix my branch protection failures with `action: fix`, I noticed that the scan just stopped abruptly at a certain repo, but there was no log (even with `ALLSTAR_LOG_LEVEL: "debug"`) to indicate what had happened.

After some investigation, I noticed that the error logging in `EnforceAll` seemed like it was swallowing the error. Basically, inside the loop that iterates over app installation repos, [the code is setting the error when `RunPolicies` fails on a repo and if the error is not nil it breaks out of the loop](https://github.com/ossf/allstar/blob/ec33a2bdb671731dffa55ab3f557f6d635b6f070/pkg/enforce/enforce.go#L109-L112). [But the code does not try to log the error until outside of the loop](https://github.com/ossf/allstar/blob/ec33a2bdb671731dffa55ab3f557f6d635b6f070/pkg/enforce/enforce.go#L125-L130). I think this does not work because the scope of the value assigned to `err` on line 109 is only within the `for` loop.

I can confirm that after making the changes in this PR and redeploying, I can see the error logged that caused my scan to fail. Incidentally, it's related to the changes in #212, so there could be more changes coming in that PR. 

I did some light refactoring of the code to make it easier to test that an error is definitely returned when encountered looping over the repos. And I did some test cleanup as well.

2022-06-17 20:17 UTC, markdboyd commented
The actual error I was seeing is documented/fixed in #220

2022-06-20 19:38 UTC, jeffmendoza requested changes

2022-06-20 19:38 UTC, jeffmendoza commented on pkg/enforce/enforce.go
> +type RunPoliciesFunc func(ctx context.Context, c *github.Client, owner, repo string, enabled bool) (EnforceRepoResults, error)
Lets use a global var here like the other test-injected functions.
```
var runPolicies ...
init() { runPolicies = runPoliciesReal }
```

2022-06-20 19:38 UTC, jeffmendoza commented on pkg/enforce/enforce.go
> +func RunPoliciesOnInstRepos(ctx context.Context, repos []*github.Repository, ghclient *github.Client, runPolicies RunPoliciesFunc) (
Can this be non-exported?

2022-06-20 19:38 UTC, jeffmendoza commented on pkg/enforce/enforce.go
> +	return instResults, owner, repoLoopErr
Add `config.ClearInstLoc(owner)` here, then remove owner from the return values.

2022-06-22 14:46 UTC, jeffmendoza approved these changes

2022-06-22 14:46 UTC, merged

2022-06-22 14:46 UTC, jeffmendoza commented
Awesome, thanks!