Implement --repo and --policy cli flags to filter down Allstar enforcement scope
ossf/allstar pull request #385
Opened 2023-03-22 11:27 UTC by Gby56

Quite a useful feature imo, especially when you want to test Allstar locally

2023-03-22 12:21 UTC, coheigea requested changes
Great improvement for testing

2023-03-22 12:21 UTC, coheigea commented on cmd/allstar/main.go
> +		if i == len(supportedPolicies)-1 {
Can we just use else here?

2023-03-22 13:04 UTC, Gby56 commented on cmd/allstar/main.go
> +		if i == len(supportedPolicies)-1 {
Done

2023-03-22 13:41 UTC, coheigea approved these changes, later dismissed

2023-03-23 18:54 UTC, Gby56 commented
I need to fix the tests !

2023-03-23 19:25 UTC, jeffmendoza commented
Sorry they were not running automatically
![image](https://user-images.githubusercontent.com/771387/227326533-b9bcb88d-6401-442a-9827-0f00401c919d.png)
I just changed the setting from middle to top here, hope that helps.

2023-03-24 15:16 UTC, jeffmendoza approved these changes

2023-03-24 15:16 UTC, merged